analyzer:
  strong-mode: true
linter:
  rules:
    - annotate_overrides
    - directives_ordering
    - empty_constructor_bodies
    - empty_statements
    - non_constant_identifier_names
    - prefer_final_fields
    - prefer_single_quotes
    - slash_for_doc_comments
